const app = {
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
};

const expenses = {
  GET_EXPENSES_REQUEST: 'GET_EXPENSES_REQUEST',
  GET_EXPENSES_SUCCESS: 'GET_EXPENSES_SUCCESS',
  GET_EXPENSES_FAILURE: 'GET_EXPENSES_FAILURE',
  UPDATE_EXPENSE: 'UPDATE_EXPENSE',
};

const comments = {
  ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
};

const receipts = {
  UPLOAD_RECEIPT_REQUEST: 'UPLOAD_RECEIPT_REQUEST',
  UPLOAD_RECEIPT_SUCCESS: 'UPLOAD_RECEIPT_SUCCESS',
  UPLOAD_RECEIPT_FAILURE: 'UPLOAD_RECEIPT_FAILURE',
};

const categories = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
};

export default {
  app,
  expenses,
  comments,
  receipts,
  categories,
};
